Add profile photo for Employee
salacsoft/lara-store-api pull request #6
Opened 2022-02-11 12:32 UTC by markbalilo123

**Overview**

- Upload avatar or profile photo of employee.

**Technical solutions**

- Edit EmployeeRequest.php.
- Add sometimes to emp_code and messages function to override the validation message.
- Add profile_photo in EmployeeResource.php.
- Add  and profile_photo to Employee model.
- Edit BaseService and make  as filename of photo.
- Create a unit test to check Employee photo if its exist in the storage.
- Create a unit test to check file type of employee photo.
- Create a unit test to check file size of employee photo.

**Dev notes**

- Tested on my local machine using postman
- Tested unit test using php artisan test. All test passed.
- In EmployeeRequest.php. Custom validation message not working.

2022-02-13 06:17 UTC, Macangel23 approved these changes

2022-02-14 00:38 UTC, salacsoft requested changes

2022-02-14 00:38 UTC, salacsoft commented on d
> +[33mcommit 5443570fe4414ffa2580bcc1d55454710bbb25a8[m[33m ([m[1;36mHEAD -> [m[1;32mfeature/employee/upload_photo[m[33m, [m[1;31morigin/develop[m[33m, [m[1;32mdevelop[m[33m)[m
ano tong file na to?

2022-02-14 04:26 UTC, salacsoft approved these changes

2022-02-14 04:26 UTC, merged